name: Seam Carving Compressing

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache vcpkg binaries
        uses: actions/cache@v3
        with:
          path: |
            vcpkg/installed
            vcpkg/downloads
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure with CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run Project in dynamic programming
        run: |
          cd build/Release
          $p = Start-Process ./seam_carving.exe -ArgumentList "../../input.jpg", "200", "300", "dp" -PassThru
            Start-Sleep -Seconds 30
            Stop-Process -Id $p.Id -ErrorAction SilentlyContinue
            Write-Host "Killed process ID $($p.Id) after 30s"
        shell: pwsh

      - name: Run Project in greedy programming
        run: |
          cd build/Release
          $p = Start-Process ./seam_carving.exe -ArgumentList "../../input.jpg", "200", "300", "gp" -PassThru
          Start-Sleep -Seconds 30
          Stop-Process -Id $p.Id -ErrorAction SilentlyContinue
          Write-Host "Killed process ID $($p.Id) after 30s"
        shell: pwsh

      # Optional: clean/build/run scripts, only if you need them for extras
      # - name: "Clean Windows"
      #   run: .\clean.bat
      # - name: "Run custom build script"
      #   run: .\build.bat
