name: Seam Carving Compressing

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache vcpkg binaries
        uses: actions/cache@v3
        with:
          path: |
            vcpkg/installed
            vcpkg/downloads
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure with CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run Project in dynamic programming
        run:  ./seam_carving.exe ../../input.jpg 200 300 dp
      
      - name: Run Project in dynamic programming
        run:  ./seam_carving.exe ../../input.jpg 200 300 gp

      # Optional: clean/build/run scripts, only if you need them for extras
      # - name: "Clean Windows"
      #   run: .\clean.bat
      # - name: "Run custom build script"
      #   run: .\build.bat
